# Generated by Django 5.0.6 on 2024-05-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_profile_client_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bird_date',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
